dataset:
  name: "MNIST"
  params:
    root: "./data"
    train: true
    download: true
  transform:
    - name: ToTensor
    - name: Normalize
      params:
        mean: [0.1307]
        std: [0.3081]
    - name: flatten

dataloader:
  params:
    batch_size: 64
    shuffle: true
    num_workers: 4
    drop_last: false

model:
  name: "autoencoder"
  params:
    input_dim: 784
    hidden_dim: 32
    type: "simple"

loss:
  name: "mse"
  params: {}

optimizer:
  name: "adam"
  params:
    lr: 0.001
    weight_decay: 0.0

scheduler:
  name: null
  params: null

trainer:
  name: "autoencoder"
  params:
    save_dir: "./checkpoints"
    model_name: "autoencoder"
    num_epochs: 1
    device: "cuda"