dataset:
  name: "super_resolution"
  params:
    lr_dir: "./data/DIV2K/train/LR"
    hr_dir: "./data/DIV2K/train/HR"
  transform:
    - name: "paired"
      params:
        crop_size: 96

dataloader:
  params:
    batch_size: 4
    shuffle: true
    num_workers: 4
    drop_last: true

model:
  name: "srgan"
  params:
    scale_factor: 4

loss:
  generator:
    name: "l1"
    params: {}
  discriminator:
    name: "gan"
    params: {}

optimizer:
  generator:
    name: "adam"
    params:
      lr: 1e-4
      betas: [0.9, 0.999]
  discriminator:
    name: "adam"
    params:
      lr: 1e-4
      betas: [0.9, 0.999]

scheduler: null

trainer:
  name: "gan"
  params:
    num_epochs: 1
    device: "cuda"