dataset:
  name: CIFAR10
  params:
    root: ./data
    train: true
    download: true
  transform:
    - name: Resize
      params: { size: [224, 224] }
    - name: ToTensor
    - name: Normalize
      params:
        mean: [0.1307]
        std: [0.3081]

dataloader:
  params:
    batch_size: 4
    shuffle: true
    num_workers: 4
    drop_last: false

model:
  name: swin
  params:
    in_channels: 3
    num_classes: 10

loss:
  name: cross_entropy
  params: {}

optimizer:
  name: adamw
  params:
    lr: 0.0003

scheduler: null

trainer:
  name: supervised
  params:
    num_epochs: 1
    device: cuda